server:
  port: 8003
  servlet:
    context-path: /apple-auth
spring:
  application: 
    name: apple-auth
  datasource:
     url: jdbc:mysql://39.106.136.45:3306/apple?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
     username: root
     password: mysql
     driver-class-name: com.mysql.jdbc.Driver
     hikari: 
       maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上 
       maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
mybatis:
    type-aliases-package: com.yzy.apple.auth.vo
    mapper-locations: classpath:mapper/auth/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8002/apple-eureka/eureka
  instance:
    prefer-ip-address: true